site_name: dev
pages:
  - index.md
  - "Textile-Cheat-Sheet.md"
  - "Image-Resize.md"
  - "Screenshots-Screencasts-Animated-Gifs.md"
  - "ffmpeg-notes.md"
  - "Unix-y-notes.md"
  - "lattice-reduction.md"
  - "GCode-Conversion.md"
  - "Git-Rename-Master.md"
  - "MkDocs-Quickstart.md"
  - "GPG-Notes.md"
  - "Git-Notes.md"
  - "Shannon-Entropy.md"
  - "Enabling-Server-HTTPS.md"
  - "BGZF-Example.md"
  - "Kelly-Criterion.md"
  - "C-Project-Template.md"
  - "Project-Organization.md"
  - "File-Naming-Conventions.md"
  - "Command-Line-Option-Loose-Standard.md"
  - "PCB-Notes.md"
  - "Coding-Style.md"
  - "Energy-Consumption-Stats.md"
  - "Simple-Sum.md"
  - "Fisher-Yates-Shuffle.md"
  - "Halting-Problem.md"
  - "Assorted-Small-Probability-Problems.md"
  - "Probability-Notes.md"
  - "Amdahls-Law.md"
  - "Is-It-Really-Open.md"
  - "Number-Theory-Notes.md"
  - "Arbitrary-Binary-Functions.md"
  - "Empirical-Laws.md"
  - "Food-CO2-Water.md"
  - "SSH-Recipes.md"
  - "Future-Predictions.md"
  - "Diophantine-Approximation.md"
  - "GCode-Common.md"
  - "Misc-Math.md"

docs_dir: 'wiki'
theme_dir: 'dev_theme'
extra:
  # for production
  #
  base : "/dev/"

  # to test
  #
  #base : "/"
